export class Cliente {

	public ClienteId: String;
    public NroCtaCte: String;
    public Nombre: String;
    public PersonaJuridica:number;
    public CategoriaId: number;
    public SeccionId: number;
    public RubroId: number;
    public Calle: String; //Calle direccion
    public Nro: String; //Nro direccion
    public Piso: String;
    public Dpto: String;
    public CodPostal: String;
    public    CPA: String;
    public    Localidad: String;
    public    AFIPProvinciaId: number;
    public    AFIPPaisId: number;
    public    Tel1: String;
    public    Tel2: String;
    public    Movil: String;
    public    Fax: String;
    public    Email: String;
    public    Web: String;
    public    NombreFantasia: String;
    public    RamoActividad: String;
    public    AntigFirma: String;
    public    Alquiler: number;
    public    AlquilerPorMes: String;
    public    AlquilerFVto: String;
    public    ContSocialF: String;
    public    ContSocialFInscrip: String;
    public    ContSocialFVto: String;
    public    Balance: number;
    public    BalanceF: String;
    public    LegalDom: String;
    public    LegalNro: String;
    public    LegalLocalidad: String;
    public    LegalProvinciaId: number;
    public    FAlta: String;
    public    Baja: number;
    public    FBaja;
    public    FUltimaModif;
    public    AFIPDocumentoId: number;
    public    NroDoc: String;
    public    AFIPResponsableId: number;
    public    CUIT: String;
    public    AFIPActividadId: number;
    public    IngBrutosCondicionId: number;
    public    IngBrutosConvenio: number;
    public    IngBrutosNro: String;
    public    IngBrutosJurisdiccionId: number;
    public    IBFVtoInscripcion: String;
    public    IngBrutosAlicuota0: number;
    public    GanaciasCondicionId: number;
    public    GanFVtoInscripcion: String;
    public    PjeExclusion: String;
    public    BoletinExclusion: String;
    public    CodImpuestoId: number;
    public    FVtoExclusion: String;
    public    RgRegimenId: number;
    public    CreditoInic: String;
    public    CreditoAutorizo1: String;
    public    CreditoF1: String;
    public    CreditoModif1: String;
    public    CreditoAutorizo2: String;
    public    CreditoF2: String;
    public    CreditoModif2: String;
    public    CreditoAutorizo3: String;
    public    CreditoF3: String;
    public    ONCCADomicilioId: number;
    public    InscriptoRFOGL: number;
    public    ONCCADerechoRegId: number;
    public    ONCCAActividadId: number;
    public    ONCCANroOperador: String;
    public    ONCCAClasificacionId: number;
    public    ListaPrecioId: String;
    public    FormaPagoId: String;
    public    ValoresA: String;
    public    VendedorId: String;
    public    VendAutorizo: String;
    public    VendF: String;
    public    CalculaInt: number;
    public    MercStock: String;
    public    MercPesos: String;
    public    Instalaciones: String;
    public    InstalPesos: String;
    public    BienesTestimonio: number;
    public    BienesPropiedad: String;
    public    BienesHipoteca: String;
    public    Rodados: number;
    public    Marca1: String;
    public    Modelo1: String;
    public    Dominio1: String;
    public    Marca2: String;
    public    Modelo2: String;
    public    Dominio2: String;
    public    Marca3: String;
    public    Modelo3: String;
    public    Dominio3: String;
    public    CodPresupuestarioId: String;
    public    Observaciones: String;
    public    cai: String;
    public    PideCategoria: String;
    public    Cuig: String;
    public    SeguroAccPersonalesF: String;
    public    AFIPRFOGL_Categoria: String;
    public    ForzarLiquidacion: String;
    public    SubListaPrecioId: String;
    public    CobradorId: String;

    constructor(       
			
    ) { 

    	this.ClienteId="";
		this.NroCtaCte="";
		this.Nombre="";
		this.PersonaJuridica= 0;
		this.CategoriaId= 0;
		this.SeccionId= 0;
		this.RubroId= 0;
		this.Calle=""; //Calle direccion
		this.Nro=""; //Nro direccion
		this.Piso="";
		this.Dpto="";
		this.CodPostal="";
		this.CPA="";
		this.Localidad="";
		this.AFIPProvinciaId=0;
		this.AFIPPaisId = 0;
		this.Tel1="";
		this.Tel2="";
		this.Movil="";
		this.Fax="";
		this.Email="";
		this.Web="";
		this.NombreFantasia="";
		this.RamoActividad="";
		this.AntigFirma="";
		this.Alquiler= 0;
		this.AlquilerPorMes="";
		this.AlquilerFVto="";
		this.ContSocialF="";
		this.ContSocialFInscrip="";
		this.ContSocialFVto="";
		this.Balance= 0;
		this.BalanceF="";
		this.LegalDom="";
		this.LegalNro="";
		this.LegalLocalidad="";
		this.LegalProvinciaId= 0;
		this.FAlta="";
		this.Baja= 0;
		this.FBaja;
		this.FUltimaModif;
		this.AFIPDocumentoId= 0;
		this.NroDoc="";
		this.AFIPResponsableId= 0;
		this.CUIT="";
		this.AFIPActividadId = 0;
		this.IngBrutosCondicionId= 0;
		this.IngBrutosConvenio= 0;
		this.IngBrutosNro="";
		this.IngBrutosJurisdiccionId= 0;
		this.IBFVtoInscripcion="";
		this.IngBrutosAlicuota0= 0;
		this.GanaciasCondicionId= 0;
		this.GanFVtoInscripcion="";
		this.PjeExclusion="";
		this.BoletinExclusion="";
		this.CodImpuestoId= 0;
		this.FVtoExclusion="";
		this.RgRegimenId= 0;
		this.CreditoInic="";
		this.CreditoAutorizo1="";
		this.CreditoF1="";
		this.CreditoModif1="";
		this.CreditoAutorizo2="";
		this.CreditoF2="";
		this.CreditoModif2="";
		this.CreditoAutorizo3="";
		this.CreditoF3="";
		this.ONCCADomicilioId= 0;
		this.InscriptoRFOGL= 0;
		this.ONCCADerechoRegId= 0;
		this.ONCCAActividadId= 0;
		this.ONCCANroOperador="";
		this.ONCCAClasificacionId= 0;
		this.ListaPrecioId="";
		this.FormaPagoId="";
		this.ValoresA="";
		this.VendedorId="";
		this.VendAutorizo="";
		this.VendF="";
		this.CalculaInt= 0;
		this.MercStock="";
		this.MercPesos="";
		this.Instalaciones="";
		this.InstalPesos="";
		this.BienesTestimonio= 0;
		this.BienesPropiedad="";
		this.BienesHipoteca="";
		this.Rodados= 0;
		this.Marca1="";
		this.Modelo1="";
		this.Dominio1="";
		this.Marca2="";
		this.Modelo2="";
		this.Dominio2="";
		this.Marca3="";
		this.Modelo3="";
		this.Dominio3="";
		this.CodPresupuestarioId="";
		this.Observaciones="";
		this.cai="";
		this.PideCategoria="";
		this.Cuig="";
		this.SeguroAccPersonalesF="";
		this.AFIPRFOGL_Categoria="";
		this.ForzarLiquidacion="";
		this.SubListaPrecioId="";
		this.CobradorId="";
    }   
}